# Generated by Django 5.2.1 on 2025-06-10 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_brand_category_product_discount_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drive_size',
            field=models.IntegerField(blank=True, choices=[(16, '16 GB'), (32, '32 GB'), (64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1 TB')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(13.0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
