# Generated by Django 5.2.1 on 2025-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
