# Generated by Django 5.2.1 on 2025-06-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_note_alter_product_screen_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
