# Generated by Django 5.2.1 on 2025-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
